rules = [
  DisableSyntax,
  OrganizeImports
]

DisableSyntax.noVars = false
DisableSyntax.noNulls = true
DisableSyntax.noThrows = true
DisableSyntax.noReturns = true
DisableSyntax.noWhileLoops = true