version = "3.10.7"
runner.dialect = scala3
maxColumn = 80
align.preset = none
continuationIndent.defnSite = 2
continuationIndent.callSite = 2
danglingParentheses.defnSite = true
danglingParentheses.callSite = true
newlines.source = keep
newlines.topLevelStatementBlankLines = [
  {
    minBreaks = 1
    blanks = 1
  }
]
verticalMultiline.atDefnSite = true
verticalMultiline.arityThreshold = 2
rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortImports
]
rewrite.redundantBraces.generalExpressions = true
rewrite.redundantBraces.defnBodies = all
rewrite.redundantBraces.ifElseExpressions = false
rewrite.redundantBraces.includeUnitMethods = false
trailingCommas = always